load("@rules_rust//rust:defs.bzl", "rust_library")
package(default_visibility = ["//visibility:public"])

rust_library(
    name = "terrain",
    srcs = ["terrain.rs"],
)

rust_library(
    name = "player",
    srcs = ["player.rs"],
)

